### PR TITLE
Revamp Console api

### PR DESCRIPTION
**Pull request by chenglou**

### CODE REVIEW

**Comment by austindd** [comment]
I am fine with this. Tbh, I was really on the fence about the global console instance with the functor API. I think this is simpler, less runtime overhead, and probably the right way to go.

**Comment by chenglou** [comment]
Thanks for you previous contribution btw.
And yeah, the idea is that the output needs to be readable by someone fresh to the ecosystem, which we're achieving here. The runtime overhead had many incorrectness in subtle cases too (not all due to how it was written, but also because... well it's JS and it's too much to explain here =) )

**Comment by chenglou** [comment]
Now we're left with only ~100 of total runtime in this lib. It means it'll be trivial for anyone to know whether they wrote the correct code by examining the output

**Comment by austindd** [comment]
Yeah, I agree it was not an ideal solution the other way. I still think it feels a bit weird coming from the JS ecosystem to have to provide the instance when you're used to just typing `console.log(data)` all the time. But at least they don't have to encounter functors in such a core module.

**Comment by chenglou** [comment]
Yeah we'll have to properly document and/or indicate in some dummy function at compile time that if you're doing `console.log` you should be using the out-of-the-box `Js.Console.log` (`Js.log` for short)

**Comment by austindd** [comment]
Yeah, that is a good idea. Also, I actually checked this repo primarily to go in an fix the polyvariant subtype for the writable stream, since I forgot to fix that earlier. I'm glad you caught it!

**Pull request merged**
